language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
before_script:
   - npm install -g firebase-tools
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN